# Generated by Django 5.2.18 on 2026-10-08 16:53

import django.contrib.postgres.constraints
from django.contrib.postgres.operations import BtreeGistExtension
import django.contrib.postgres.fields.ranges
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        BtreeGistExtension(),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Nido Hotel & Hostel', max_length=100)),
                ('subtitle', models.CharField(blank=True, default='Recepción', max_length=120)),
                ('primary_color', models.CharField(default='#153a43', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Usá un color hexadecimal de seis dígitos.')])),
                ('secondary_color', models.CharField(default='#0d766e', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Usá un color hexadecimal de seis dígitos.')])),
                ('accent_color', models.CharField(default='#e9a23b', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Usá un color hexadecimal de seis dígitos.')])),
                ('logo', models.ImageField(blank=True, upload_to='brand/')),
                ('cover', models.ImageField(blank=True, upload_to='brand/')),
                ('sections', models.JSONField(default=dict)),
                ('currency', models.CharField(default='ARS', max_length=3)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('kind', models.CharField(choices=[('PRIVATE', 'Privada'), ('SHARED', 'Compartida')], max_length=10)),
                ('capacity', models.PositiveSmallIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1)])),
                ('image', models.ImageField(blank=True, upload_to='rooms/')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest', models.CharField(max_length=120)),
                ('contact', models.CharField(blank=True, max_length=120)),
                ('document', models.CharField(blank=True, max_length=80)),
                ('guests', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('status', models.CharField(choices=[('CONFIRMED', 'Confirmada'), ('IN_HOUSE', 'Alojado'), ('CHECKED_OUT', 'Finalizada'), ('CANCELLED', 'Cancelada')], default='CONFIRMED', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('checked_out_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['start', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('end__gt', models.F('start'))), name='reservation_positive_stay')],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('cleaning', models.CharField(choices=[('CLEAN', 'Lista'), ('DIRTY', 'Pendiente'), ('CLEANING', 'En limpieza')], default='CLEAN', max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='units', to='pms.room')),
            ],
            options={
                'ordering': ['room__name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('notes', models.TextField(blank=True)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('blocking', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('OPEN', 'Pendiente'), ('IN_PROGRESS', 'En curso'), ('DONE', 'Resuelta')], default='OPEN', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance', to='pms.room')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pms.unit')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CleaningTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('IN_PROGRESS', 'En curso'), ('DONE', 'Lista')], default='PENDING', max_length=12)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cleaning_tasks', to='pms.unit')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('active', models.BooleanField(default=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='pms.reservation')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='pms.unit')),
            ],
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('CHARGE', 'Cargo'), ('PAYMENT', 'Cobro')], max_length=10)),
                ('description', models.CharField(max_length=160)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('method', models.CharField(blank=True, choices=[('CASH', 'Efectivo'), ('CARD', 'Tarjeta'), ('TRANSFER', 'Transferencia'), ('OTHER', 'Otro')], max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger', to='pms.reservation')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='ledger_positive_amount')],
            },
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.UniqueConstraint(fields=('room', 'name'), name='unique_unit_name'),
        ),
        migrations.AddConstraint(
            model_name='maintenance',
            constraint=models.CheckConstraint(condition=models.Q(('end__gt', models.F('start'))), name='maintenance_positive_period'),
        ),
        migrations.AddConstraint(
            model_name='cleaningtask',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'DONE'), _negated=True), fields=('unit',), name='one_open_cleaning_task'),
        ),
        migrations.AddConstraint(
            model_name='allocation',
            constraint=models.CheckConstraint(condition=models.Q(('end__gt', models.F('start'))), name='allocation_positive_stay'),
        ),
        migrations.AddConstraint(
            model_name='allocation',
            constraint=models.UniqueConstraint(fields=('reservation', 'unit'), name='unique_reservation_unit'),
        ),
        migrations.AddConstraint(
            model_name='allocation',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('active', True)), expressions=[('unit', '='), (models.Func(models.F('start'), models.F('end'), models.Value('[)'), function='DATERANGE', output_field=django.contrib.postgres.fields.ranges.DateRangeField()), '&&')], name='no_overlapping_active_allocation'),
        ),
    ]
