# Generated by Django 5.2.18 on 2026-10-09 17:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pms', '0002_reservation_account_reviewed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('configuration', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImportDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(blank=True, max_length=200)),
                ('fingerprint', models.CharField(max_length=64)),
                ('source', models.JSONField(default=dict)),
                ('configuration', models.JSONField(default=dict)),
                ('decisions', models.JSONField(default=dict)),
                ('preview', models.JSONField(default=dict)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('state', models.CharField(choices=[('DRAFT', 'Borrador'), ('APPLIED', 'Aplicado'), ('DISCARDED', 'Descartado')], default='DRAFT', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='imports.importprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actions', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('draft', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='batch', to='imports.importdraft')),
            ],
        ),
        migrations.CreateModel(
            name='ImportBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.UUIDField(default=uuid.uuid4)),
                ('signature', models.CharField(blank=True, max_length=64)),
                ('content', models.JSONField(default=dict)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_bindings', to='pms.reservation')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='imports.importprofile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('profile', 'source_id'), name='unique_import_source'), models.UniqueConstraint(fields=('profile', 'reservation'), name='unique_import_reservation')],
            },
        ),
    ]
